"""GreyEye shared contracts — single source of truth for cross-service types."""

from .enums import (
    AlertConditionType,
    AlertSeverity,
    AlertStatus,
    CameraSourceType,
    CameraStatus,
    ClassificationMode,
    CoarseFallbackClass,
    CrossingDirection,
    LineDirection,
    SiteStatus,
    UserRole,
    VehicleClass12,
)
from .errors import ErrorBody, ErrorCode, ErrorDetail, ErrorResponse
from .events import (
    BUCKET_DURATION_MINUTES,
    AlertEvent,
    CameraHealthEvent,
    TrackEvent,
    VehicleCrossingEvent,
    compute_bucket_start,
)
from .geometry import (
    BoundingBox,
    CountingLine,
    DirectionVector,
    LanePolyline,
    Point2D,
    ROIPolygon,
    ROIPresetGeometry,
)
from .nats_dlq import DLQHandler
from .nats_streams import (
    ALL_STREAM_NAMES,
    CONSUMER_AGGREGATOR_CROSSINGS,
    CONSUMER_AGGREGATOR_RECOMPUTE,
    CONSUMER_DEFS,
    CONSUMER_DEFS_BY_DURABLE,
    CONSUMER_INFERENCE_WORKER,
    CONSUMER_NOTIFICATION_CROSSINGS,
    CONSUMER_NOTIFICATION_HEALTH,
    STREAM_ALERTS,
    STREAM_COMMANDS,
    STREAM_CROSSINGS,
    STREAM_DEFS,
    STREAM_DEFS_BY_NAME,
    STREAM_DLQ,
    STREAM_FRAMES,
    STREAM_HEALTH,
    STREAM_TRACKS,
    SUBJECT_ALERTS,
    SUBJECT_COMMANDS,
    SUBJECT_CROSSINGS,
    SUBJECT_DLQ,
    SUBJECT_FRAMES,
    SUBJECT_HEALTH,
    SUBJECT_RECOMPUTE,
    SUBJECT_TRACKS,
    ConsumerDef,
    StreamDef,
    dlq_subject_for,
    publish_to_dlq,
)
from .pagination import PaginatedResponse, PaginationMeta, PaginationParams
from .encryption import FieldEncryptor
from .privacy import (
    AUDIO_CAPTURE_ENABLED,
    DataRetentionPolicy,
    PrivacySettings,
    RedactionMode,
)

__all__ = [
    "ALL_STREAM_NAMES",
    "AUDIO_CAPTURE_ENABLED",
    "BUCKET_DURATION_MINUTES",
    "AlertConditionType",
    "AlertEvent",
    "AlertSeverity",
    "AlertStatus",
    "BoundingBox",
    "CameraHealthEvent",
    "CameraSourceType",
    "CameraStatus",
    "ClassificationMode",
    "CoarseFallbackClass",
    "ConsumerDef",
    "CountingLine",
    "CrossingDirection",
    "DirectionVector",
    "ErrorBody",
    "ErrorCode",
    "ErrorDetail",
    "ErrorResponse",
    "FieldEncryptor",
    "DataRetentionPolicy",
    "LanePolyline",
    "LineDirection",
    "PaginatedResponse",
    "PaginationMeta",
    "PaginationParams",
    "Point2D",
    "PrivacySettings",
    "ROIPolygon",
    "ROIPresetGeometry",
    "RedactionMode",
    "SiteStatus",
    "StreamDef",
    "TrackEvent",
    "UserRole",
    "VehicleClass12",
    "VehicleCrossingEvent",
    # NATS consumer durable names
    "CONSUMER_AGGREGATOR_CROSSINGS",
    "CONSUMER_AGGREGATOR_RECOMPUTE",
    "CONSUMER_DEFS",
    "CONSUMER_DEFS_BY_DURABLE",
    "CONSUMER_INFERENCE_WORKER",
    "CONSUMER_NOTIFICATION_CROSSINGS",
    "CONSUMER_NOTIFICATION_HEALTH",
    # NATS stream names
    "STREAM_ALERTS",
    "STREAM_COMMANDS",
    "STREAM_CROSSINGS",
    "STREAM_DEFS",
    "STREAM_DEFS_BY_NAME",
    "STREAM_DLQ",
    "STREAM_FRAMES",
    "STREAM_HEALTH",
    "STREAM_TRACKS",
    # NATS subject prefixes
    "SUBJECT_ALERTS",
    "SUBJECT_COMMANDS",
    "SUBJECT_CROSSINGS",
    "SUBJECT_DLQ",
    "SUBJECT_FRAMES",
    "SUBJECT_HEALTH",
    "SUBJECT_RECOMPUTE",
    "SUBJECT_TRACKS",
    "compute_bucket_start",
    "dlq_subject_for",
    "publish_to_dlq",
    "DLQHandler",
]
