replicaCount: 2

image:
  repository: greyeye/api-gateway
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 200m

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

env:
  TLS_ENABLED: "false"
  AUTH_SERVICE_HOST: auth-service
  CONFIG_SERVICE_HOST: config-service
  INGEST_SERVICE_HOST: ingest-service
  REPORTING_API_HOST: reporting-api
  AGGREGATOR_HOST: aggregator
  NOTIFICATION_SERVICE_HOST: notification-service

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
